### ISSUE TITLE
If dataset shrinks, we fail when updating datapackage

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl-archiver#32]
I simulated "a bunch of files go offline" by only returning one hyperlink from `get_hyperlinks`:

```diff
diff --git a/src/pudl_archiver/archivers/classes.py b/src/pudl_archiver/archivers/classes.py
index 1883d0c..35b85bc 100644
--- a/src/pudl_archiver/archivers/classes.py
+++ b/src/pudl_archiver/archivers/classes.py
@@ -157,7 +157,7 @@ class AbstractDatasetArchiver(ABC):
                 f"Make sure your filter_pattern is correct or if the structure of the {url} page changed."
             )

-        return hyperlinks
+        return list(hyperlinks)[:1]

     async def create_archive(self):
         """Download all resources and create an archive for upload.
```

Then when I ran  `pudl_archiver --sandbox --datasets eia861` I got:
```
[2023-01-20 14:10:49 [    INFO] catalystcoop.pudl_archiver.zenodo.api_client:317 GET https://sandbox.zenodo.org/api/deposit/depositions - get
deposition
2023-01-20 14:10:54 [    INFO] catalystcoop.pudl_archiver.zenodo.api_client:197 GET https://sandbox.zenodo.org/api/deposit/depositions/1149408/
files
2023-01-20 14:10:57 [    INFO] catalystcoop.pudl_archiver.archivers.classes:75 Archiving eia861
2023-01-20 14:11:07 [    INFO] catalystcoop.pudl_archiver.archivers.classes:176 Downloaded /var/folders/7q/28j531_d151fn0d3831ql0c00000gr/T/tmp
5w_m4p_9/eia861-1999.zip.
2023-01-20 14:11:07 [    INFO] catalystcoop.pudl_archiver.zenodo.api_client:259 Adding eia861-1999.zip to deposition.
2023-01-20 14:11:07 [    INFO] catalystcoop.pudl_archiver.zenodo.api_client:439 Creating new datapackage.json for eia861
2023-01-20 14:11:07 [    INFO] catalystcoop.pudl_archiver.zenodo.api_client:443 GET https://sandbox.zenodo.org/api/deposit/depositions/1149408/
files - getting file list for datapackage
Encountered exceptions, showing traceback for last one: ["('eia861', KeyError('eia861-2006.zip'))"]
Traceback (most recent call last):
  File "/Users/dazhong-catalyst/mambaforge/envs/pudl-archiver-toml/bin/pudl_archiver", line 8, in <module>
    sys.exit(main())
  File "/Users/dazhong-catalyst/work/pudl-archiver/src/pudl_archiver/cli.py", line 58, in main
    asyncio.run(archive_datasets(**vars(args)))
  File "/Users/dazhong-catalyst/mambaforge/envs/pudl-archiver-toml/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/dazhong-catalyst/mambaforge/envs/pudl-archiver-toml/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/dazhong-catalyst/work/pudl-archiver/src/pudl_archiver/__init__.py", line 99, in archive_datasets
    raise exceptions[-1][1]                                                                                                                      File "/Users/dazhong-catalyst/work/pudl-archiver/src/pudl_archiver/__init__.py", line 47, in archive_dataset
    await archiver.create_archive()                                                                                                              File "/Users/dazhong-catalyst/work/pudl-archiver/src/pudl_archiver/archivers/classes.py", line 180, in create_archive
    await self.deposition.add_files(resource_dict)
  File "/Users/dazhong-catalyst/work/pudl-archiver/src/pudl_archiver/zenodo/api_client.py", line 283, in add_files
    await self.update_datapackage(resources)
  File "/Users/dazhong-catalyst/work/pudl-archiver/src/pudl_archiver/zenodo/api_client.py", line 454, in update_datapackage
    datapackage = DataPackage.from_filelist(
  File "/Users/dazhong-catalyst/work/pudl-archiver/src/pudl_archiver/frictionless.py", line 98, in from_filelist
    resources=[
  File "/Users/dazhong-catalyst/work/pudl-archiver/src/pudl_archiver/frictionless.py", line 99, in <listcomp>
    Resource.from_file(file, resources[file.filename].partitions)
KeyError: 'eia861-2006.zip'
```

This appears to be because in `frictionless.DataPackage.from_filelist` we have

```
            resources=[
                Resource.from_file(file, resources[file.filename].partitions)
                for file in files
            ]
```

Where `files` is the list of files that were in the deposition before we started doing all these edits and `resources` is the list of resources we downloaded. Then if there's a file in `files` that's not in `resources` we hit that `KeyError`.

We should probably pass in the list of files for the deposition version post-edits - so maybe we should:
* stage changes for normal files
* apply changes
* refresh deposition information
* stage changes for datapackage
* apply changes for datapackage
* publish

@zschira does this analysis make sense?

**Comment by jdangerx** [comment]
(It seems like this was happening on `main` but it looks like the above behavior *shouldn't* happen on `main`.... investigating further.)

**Comment by zschira** [comment]
This approach seems right to me. It also might be smart to add a check to verify that the files we get after refreshing deposition info matches what we expect from the staged changes, and raise an error if they don't (or perhaps do a retry to see if the deposition hasn't refreshed on zenodo's end).

I am trying to figure out why I didn't run across this before, because I do remember doing some tests where files were deleted, and never ran into a problem. Perhaps this arose from the refactor somehow?

**Comment by jdangerx** [comment]
I thought so, but the `ZenodoDepositor` isn't being used in `main` yet, and I was able to repro in `main`.

**Comment by jdangerx** [comment]
(in `main` there's code that looks like it tries to fetch the deposition's `files` link - which should get the latest set)

**Comment by jdangerx** [comment]
Oh, but fetching the latest files doesn't get the deletes because they haven't happened yet. That makes sense to me.

**Comment by zschira** [comment]
They should've happened on the draft deposition though, right?

**Comment by zschira** [comment]
Oh I guess `update_datapackage` is happening before apply changes, so the files we get will just be the original state. I think we just need to swap that order

**Comment by jdangerx** [comment]
Yeah, I have a tiny PR coming in a second.
