### ISSUE TITLE
Error installing pudl-archiver: Don't know machine value for archs=()

### ISSUE THREAD

**Issue by katie-lamb** [catalyst-cooperative/pudl-archiver#35]
When I try and create the `pudl-archiver` environment using

`conda env create --file environment.yml`

I get `ValueError: Don't know machine value for archs=()` when installing pip dependencies.

This is the stack trace.

```
Traceback (most recent call last):
  File "/Users/katielamb/miniconda3/envs/pudl-archiver/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/katielamb/miniconda3/envs/pudl-archiver/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/katielamb/miniconda3/envs/pudl-archiver/lib/python3.10/site-packages/pip/__main__.py", line 31, in <module>
    sys.exit(_main())
  File "/Users/katielamb/miniconda3/envs/pudl-archiver/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
  File "/Users/katielamb/miniconda3/envs/pudl-archiver/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
  File "/Users/katielamb/miniconda3/envs/pudl-archiver/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    self.handle_pip_version_check(options)
  File "/Users/katielamb/miniconda3/envs/pudl-archiver/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 179, in handle_pip_version_check
    session = self._build_session(
  File "/Users/katielamb/miniconda3/envs/pudl-archiver/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 125, in _build_session
    session = PipSession(
  File "/Users/katielamb/miniconda3/envs/pudl-archiver/lib/python3.10/site-packages/pip/_internal/network/session.py", line 343, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/Users/katielamb/miniconda3/envs/pudl-archiver/lib/python3.10/site-packages/pip/_internal/network/session.py", line 175, in user_agent
    setuptools_dist = get_default_environment().get_distribution("setuptools")
  File "/Users/katielamb/miniconda3/envs/pudl-archiver/lib/python3.10/site-packages/pip/_internal/metadata/__init__.py", line 75, in get_default_environment
    return select_backend().Environment.default()
  File "/Users/katielamb/miniconda3/envs/pudl-archiver/lib/python3.10/site-packages/pip/_internal/metadata/__init__.py", line 63, in select_backend
    from . import pkg_resources
  File "/Users/katielamb/miniconda3/envs/pudl-archiver/lib/python3.10/site-packages/pip/_internal/metadata/pkg_resources.py", line 8, in <module>
    from pip._vendor import pkg_resources
  File "/Users/katielamb/miniconda3/envs/pudl-archiver/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 959, in <module>
    class Environment:
  File "/Users/katielamb/miniconda3/envs/pudl-archiver/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 963, in Environment
    self, search_path=None, platform=get_supported_platform(),
  File "/Users/katielamb/miniconda3/envs/pudl-archiver/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 190, in get_supported_platform
    plat = get_build_platform()
  File "/Users/katielamb/miniconda3/envs/pudl-archiver/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 395, in get_build_platform
    plat = get_platform()
  File "/Users/katielamb/miniconda3/envs/pudl-archiver/lib/python3.10/sysconfig.py", line 745, in get_platform
    osname, release, machine = _osx_support.get_platform_osx(
  File "/Users/katielamb/miniconda3/envs/pudl-archiver/lib/python3.10/_osx_support.py", line 556, in get_platform_osx
    raise ValueError(
ValueError: Don't know machine value for archs=()

failed

CondaEnvException: Pip failed
```

I'm running macOS Monterey. Has anyone else with macOS successfully created the environment?

I tried taking out the optional dependencies (`dev`, `docs`, `tests`) but still got the error. 

Maybe it's the `build-system` part of `pyproject.toml`?
```
[build-system]
requires = [
    "setuptools<66,>=61.0"
]
build-backend = "setuptools.build_meta"
```

**Comment by bendnorman** [comment]
This is bonkers. When I create a new python 3.10 environment using this command:
```
mabma create -n "pudl-archiver" python=3.10.0
```
then run `pip install -e .` inside the env I don't get the error.

**Comment by bendnorman** [comment]
I'm pretty stumped on this one because similar packages and environments like `pudl` and `cheshire` are working.

**Comment by jdangerx** [comment]
I think it's because `pudl-archiver` includes the string `-arch`: https://bugs.python.org/issue47154

**Comment by jdangerx** [comment]
@bendnorman I haven't been able to repro on 3.10.8 (attempting 3.10.0 now) - was there any particular reason you were using 3.10.0?

**Comment by jdangerx** [comment]
When I look for the CFLAGS that are set by my python interpreter in the mamba environment I get this:
```> ~/mambaforge/envs/pudl-archiver-test/bin/python3-config --cflags
-I/Users/dazhong-catalyst/mambaforge/envs/pudl-archiver-test/include/python3.10 -I/Users/dazhong-catalyst/mambaforge/envs/pudl-archiver-test/include/python3.10 -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/dazhong-catalyst/mambaforge/envs/pudl-archiver-test/include -arch arm64 -fPIC -O2 -isystem /Users/dazhong-catalyst/mambaforge/envs/pudl-archiver-test/include -arch arm64```

Which doesn't seem to be causing any problems for me, but maybe if people who can reproduce it (@bendnorman or @katie-lamb) try making the environment under a different name it might work?

**Comment by jdangerx** [comment]
@katie-lamb what do you get with
```python
>>> sysconfig.get_config_var("CFLAGS")
'-Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O2 -Wall -fPIC   -O2  -isystem /Users/dazhong-catalyst/mambaforge/envs/pudl-archiver-test/include -arch arm64  -fPIC   -O2  -isystem /Users/dazhong-catalyst/mambaforge/envs/pudl-archiver-test/include -arch arm64 '
```

**Comment by katie-lamb** [comment]
@jdangerx In the working environment which I've renamed `pudl-saver` I get the following:
'-Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC  -O2  -isystem /Users/katielamb/miniconda3/envs/pudl-saver/include -fPIC  -O2  -isystem /Users/katielamb/miniconda3/envs/pudl-saver/include '

No `-arch`!
